=== mouad333/Full_Examen_XML_Webservice/Controle_enset_xml_webService/xml_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >

    <xs:element name="releve">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:date" name="dateReleve"/>
                <xs:element type="xs:short" name="solde"/>
                <xs:element name="operations">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="operation" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="xs:string" name="type" use="optional"/>
                                            <xs:attribute type="xs:date" name="date" use="optional"/>
                                            <xs:attribute type="xs:int" name="montant" use="optional"/>
                                            <xs:attribute type="xs:string" name="description" use="optional"/>
                                            <xs:attribute type="xs:string" name="desciption" use="optional"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:date" name="dateDebut"/>
                        <xs:attribute type="xs:date" name="dateFin"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:integer" name="RIB"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mouad333/Full_Examen_XML_Webservice/Controle_enset_xml_webService/releve_schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<releve RIB="011112223334445556666" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/hp/Documents/Controle_enset_xml_webService/xml_schema.xsd">
    <dateReleve>2021-11-30</dateReleve>
    <solde>14500</solde>
    <operations dateDebut="2021-11-01" dateFin="2021-11-29">
        <operation type="CREDIT" date="2021-11-01" montant="9000" description="Vers Espèce"></operation>
        <operation type="DEBIT" date="2021-11-10" montant="3400" description="chèque Guichet"></operation>
        <operation type="DEBIT" date="2021-11-15" montant="120" description="Prélévement Assurance"></operation>
        <operation type="CREDIT" date="2021-11-29" montant="70000" description="Virement"></operation>
    </operations>
</releve>
